const KNOWLEDGE = `
A&A Asset Team: «Превращаем зависшие активы бизнеса в деньги».
Работаем с продажей сложного и зависшего имущества бизнеса: производственные базы, склады, ангары, промышленные участки, коммерческая недвижимость, оборудование, спецтехника, складские остатки и неликвидные ТМЦ.
`;

function jsonResponse(data, status = 200) { return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8' } }); }
const normalize = (text) => String(text || '').toLowerCase().replace(/ё/g, 'е');
const getMessage = (u) => u?.message || u?.edited_message || null;
const getText = (u) => u?.message?.text || u?.edited_message?.text || '';
const getUser = (f = {}) => ({ id: f.id || '', fullName: `${f.first_name || ''} ${f.last_name || ''}`.trim(), username: f.username ? `@${f.username}` : '' });
const sessionKey = (chatId) => `telegram-lead:${chatId}`;
const emptySession = () => ({ lead: {}, messages: [], earlyManagerNotified: false, fullManagerNotified: false, managerNotified: false, notifiedFields: {}, lastSupplementHash: '' });

async function loadSession(env, chatId) { if (!env.CHAT_MEMORY) return emptySession(); const raw = await env.CHAT_MEMORY.get(sessionKey(chatId)); if (!raw) return emptySession(); try { const p = JSON.parse(raw); return { ...emptySession(), ...p, earlyManagerNotified: Boolean(p.earlyManagerNotified || p.managerNotified), fullManagerNotified: Boolean(p.fullManagerNotified) }; } catch { return emptySession(); } }
async function saveSession(env, chatId, session) { if (env.CHAT_MEMORY) await env.CHAT_MEMORY.put(sessionKey(chatId), JSON.stringify(session), { expirationTtl: 60 * 60 * 24 * 14 }); }

function detectAssetType(text){const t=normalize(text); if(t.includes('база'))return 'производственная база'; if(t.includes('склад')||t.includes('ангар'))return 'склад / ангар'; if(t.includes('участ')||t.includes('земл'))return 'земельный участок'; if(t.includes('оборуд'))return 'оборудование'; if(t.includes('спецтех'))return 'спецтехника'; if(t.includes('тмц')||t.includes('неликвид'))return 'ТМЦ / складские остатки'; if(t.includes('помещ')||t.includes('недвиж'))return 'коммерческая недвижимость'; return '';}
function extractPatch(text){const t=normalize(text); const p={}; const at=detectAssetType(text); if(at)p.asset_type=at; if(t.includes('собственник'))p.role='собственник'; if(t.includes('представитель'))p.role='представитель'; if(t.includes('фото'))p.photos='есть / упомянуты'; if(t.includes('документ'))p.documents='документы упомянуты'; const a=text.match(/\d+[\d\s,.]*(?:м2|м²|кв\.?\s*м|сот|га)/i)?.[0]; if(a)p.area=a; const pr=text.match(/\d+[\d\s,.]*(?:млн|тыс|руб|₽)/i)?.[0]; if(pr)p.price=pr; const per=text.match(/(?:\d+\s*(?:год|года|лет|месяц|месяца|месяцев)|полгода)/i)?.[0]; if(per)p.selling_period=per; const url=text.match(/https?:\/\/\S+/)?.[0]; if(url)p.url=url; const phone=text.match(/(?:\+7|7|8)\D{0,3}\(?\d{3}\)?\D{0,3}\d{3}\D{0,3}\d{2}\D{0,3}\d{2}/)?.[0]; const email=text.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/)?.[0]; if(phone||email)p.contact=[phone,email].filter(Boolean).join(', '); if(t.includes('москва'))p.location='Москва'; if(t.includes('московская область'))p.location='Московская область'; return p;}

const mergeLead=(a,b)=>({...(a||{}),...(b||{})});
const hasAssetContext=(lead,text)=>Boolean(lead.asset_type||detectAssetType(text));
const isFullLeadReady=(lead)=>Boolean(lead.asset_type&&lead.location&&lead.area&&lead.price&&lead.selling_period&&lead.role);
const shouldNotifyEarlyLead=(lead,text)=>Boolean(hasAssetContext(lead,text)&&lead.asset_type&&(lead.location||lead.price||lead.area||lead.url));
const hasCallIntent=(text)=>['жду звонка','позвоните','готов обсудить','жду связи','можно звонить','свяжитесь','наберите'].some((w)=>normalize(text).includes(w));

function systemPrompt(){return `Ты — AI-оператор A&A Asset Team по первичному разбору и диагностике активов бизнеса.
Ты не просто собираешь анкету. Ты проводишь первичную диагностику актива: что продается, где находится, почему зависло, какие данные нужны для оценки ликвидности и подготовки маршрута реализации.
${KNOWLEDGE}
Стиль: деловой, спокойный, профессиональный. Без гарантий цены и продажи. Без юридических заключений и агрессивных продаж. Не задавай 10 вопросов сразу: максимум 2-3 ключевых вопроса. Не спрашивай повторно известные данные. Если клиент дал контакт — подтверди передачу. Если клиент спросил про аренду, верни фокус к продаже/реализации активов.`;}
async function askOpenAI(env,{text,session,user}){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:env.OPENAI_MODEL||'gpt-4.1-mini',input:[{role:'system',content:systemPrompt()},{role:'user',content:JSON.stringify({current_message:text,collected_data:session.lead,recent_history:session.messages.slice(-8),telegram_user:user})}],temperature:0.45,max_output_tokens:600})}); if(!r.ok) throw new Error(await r.text()); const d=await r.json(); return d.output_text||'';}
function fallbackReply(text,session){if(hasCallIntent(text)) return session.lead.contact?'Принял. Передаю информацию на разбор. Специалист свяжется с вами по указанному контакту.':'Принял. Оставьте, пожалуйста, удобный телефон или другой контакт для связи — передам информацию специалисту.'; return 'Принял. Зафиксировал. Уточните, пожалуйста: локацию, площадь/объем и ориентировочную цену актива.';}
async function sendTelegram(env,chatId,text,replyTo){const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chatId,text,reply_to_message_id:replyTo||undefined,disable_web_page_preview:true})}); if(!r.ok) throw new Error(await r.text());}
async function sendManager(env,text){if(!env.MANAGER_CHAT_ID) return; await sendTelegram(env,env.MANAGER_CHAT_ID,text);}
const startGreeting=()=>"Здравствуйте. Я AI-оператор A&A Asset Team по первичному разбору активов бизнеса.\n\nПомогу собрать ключевые данные по объекту и понять следующий шаг для продажи или реализации.\n\nМы работаем с зависшими и сложными активами: производственные базы, склады, ангары, коммерческая недвижимость, оборудование, спецтехника, ТМЦ и неликвидные остатки.\n\nНапишите, что нужно реализовать: что за актив, где находится, примерная площадь или объем, цена и сколько времени уже продается.";
function card(prefix,user,lead,last,newFields=[]){return [prefix,'',`Клиент: ${user.fullName||'не указано'} ${user.username||''}`.trim(),`user_id: ${user.id||'не указано'}`,newFields.length?`Новые данные: ${newFields.join(', ')}`:'',`Тип актива: ${lead.asset_type||'не указано'}`,`Локация: ${lead.location||'не указано'}`,`Площадь / объем: ${lead.area||'не указано'}`,`Цена: ${lead.price||'не указано'}`,`Срок продажи: ${lead.selling_period||'не указано'}`,`Контакт: ${lead.contact||'не указано'}`,`Фото / ссылка: ${lead.photos||lead.url||'не указано'}`,`Документы: ${lead.documents||'не указано'}`,`Кто обратился: ${lead.role||'не указано'}`,'',`Последнее сообщение: ${last}`].filter(Boolean).join('\n');}
function detectSupplementFields(session,prev,next,text){if(!session.fullManagerNotified) return []; const n=session.notifiedFields||{}; const f=[]; if(!prev.contact&&next.contact&&!n.contact) f.push('contact'); if(!prev.url&&next.url&&!n.url) f.push('url'); if(!prev.documents&&next.documents&&!n.documents) f.push('documents'); if(!prev.photos&&next.photos&&!n.photos) f.push('photos'); if(hasCallIntent(text)&&!n.call_intent&&!n.contact) f.push('call_intent'); return f;}

export async function onRequestPost({request,env}){ if(!env.TELEGRAM_BOT_TOKEN) return jsonResponse({ok:false,error:'Missing TELEGRAM_BOT_TOKEN'},200); const update=await request.json(); const message=getMessage(update); const text=getText(update).trim(); if(!message||!text) return jsonResponse({ok:true,skipped:true}); if(message.from?.is_bot) return jsonResponse({ok:true,skipped:true}); const chatId=message.chat.id; const user=getUser(message.from);
 if(text.startsWith('/start')){ await saveSession(env,chatId,emptySession()); await sendTelegram(env,chatId,startGreeting(),message.message_id); return jsonResponse({ok:true,event:'start'});} if(text.startsWith('/')) return jsonResponse({ok:true,skipped:true});
 const session=await loadSession(env,chatId); const prev={...(session.lead||{})}; session.lead=mergeLead(session.lead,extractPatch(text)); session.messages=[...(session.messages||[]),{role:'client',text,at:new Date().toISOString()}].slice(-20);
 let reply=''; if(env.OPENAI_API_KEY){try{reply=await askOpenAI(env,{text,session,user});}catch(e){console.error('OpenAI fallback',e.message);}} if(!reply) reply=fallbackReply(text,session); if(hasCallIntent(text)) reply=fallbackReply(text,session); await sendTelegram(env,chatId,reply,message.message_id);
 if(isFullLeadReady(session.lead)&&!session.fullManagerNotified){await sendManager(env,card('✅ ПОЛНАЯ ЗАЯВКА ИЗ TELEGRAM-БОТА',user,session.lead,text)); session.fullManagerNotified=true; session.earlyManagerNotified=true;}
 else if(shouldNotifyEarlyLead(session.lead,text)&&!session.earlyManagerNotified){await sendManager(env,card('🟡 РАННИЙ ЛИД ИЗ TELEGRAM-БОТА',user,session.lead,text)); session.earlyManagerNotified=true;}
 const sup=detectSupplementFields(session,prev,session.lead,text); if(sup.length){const hash=sup.sort().join('|')+'|'+(session.lead.contact||'')+'|'+(session.lead.url||''); if(hash!==session.lastSupplementHash){await sendManager(env,card('📎 ДОПОЛНЕНИЕ К ЗАЯВКЕ ИЗ TELEGRAM-БОТА',user,session.lead,text,sup)); session.lastSupplementHash=hash; session.notifiedFields={...(session.notifiedFields||{})}; for(const x of sup) session.notifiedFields[x]=true;}}
 session.messages=[...session.messages,{role:'bot',text:reply,at:new Date().toISOString()}].slice(-20); await saveSession(env,chatId,session); return jsonResponse({ok:true}); }

export async function onRequestGet(){ return jsonResponse({ ok:true, mode:'stateful-dialog-v3-professional-two-stage-leads', memory:'requires Cloudflare KV binding CHAT_MEMORY' }); }
